### ISSUE TITLE
Stuck at Loading, please wait

### ISSUE THREAD

**Issue by cihangoksu** [hwatheod/gnubg-web#1]
Hi, first I really like to thank for this web-interface of gnubg software, it seems great! I would like to run it on my localhost, but it, unfortunately, gets stuck on "Loading, please wait page". The error I got after inspecting the page-console is: "Uncaught (in promise) getpwuid: TODO" in gnubg.js.
Is there any way to resolve it? Thanks..

**Comment by hwatheod** [comment]
Which version of Emscripten are you using?

**Comment by cihangoksu** [comment]
1.39.13

**Comment by cihangoksu** [comment]
I sorted out after your comment!!!1 thank you very much. I simply downloaded version 1.39.3, and activated it. It solved the issue :-)

**Comment by hwatheod** [comment]
Added a hack to build.sh to replace the getpwuid stub (which throws an exception) so it just returns 0. Now it will build on the latest Emscripten 2.0.23.  The hack can be removed if https://github.com/emscripten-core/emscripten/issues/13219 is fixed.
